complexity:
  LongMethod:
    active: true
    threshold: 85
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 12
  TooManyFunctions:
    active: true
    thresholdInInterfaces: 15
    thresholdInClasses: 15
    thresholdInObjects: 15

naming:
  InvalidPackageDeclaration:
    active: false

style:
  MaxLineLength:
    active: true
    maxLineLength: 140
